#!/bin/sh

PATH=$PATH:$HOME/.gem/ruby/1.9.1/bin

path="$HOME/html/jekyll"

filelist=                            \
   $path/_site/index.html            \
   $path/_site/calendar/index.html   \

python $path/ical/ical.py ${filelist}
