source: ./_source
destination: ./_site

name: HaSi e.V.
description: Dein Hackspace in Siegen
url: http://www.hasi.it/
license: CC BY-NC-SA 3.0

excerpt_separator: "<!-- break -->"

podcast:
  path: http://files.hasi.it/podcast/
  description: "Techink respektlos begegnen! Das Hasi ist eine Gemeinschaft vom technikinteressierten Menschen, die an Hard- und Software rumbasteln, versuchen sie zu verstehen uns sich gegenseitig zu erklären. In diesem Podcast wollen sie den Rest der Welt daran teil haben lassen"
  subtitle: "Hodor Hodor Subtitle HODOR!"
  keywords: [Hacking, Technologie, Bildung, Kultur, Magie] 
  itunes_categories: [Education, Software How-To, Training]

markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: table
  parse_block_html: true
assets:
  sources:
  - _assets/stylesheets
  - _assets/webfonts
  - _assets/images
  cachebust: none

info:
  name: Hasi e.V.
  mail: kontakt@hasi.it
  street: Effertsufer 104
  country: 57072 Siegen (NRW)

safe: false

navigation:
- title: Home
  url: /
- title: Wer sind wir?
  url: /about/
- title: Talks
  url: /talks/
- title: Termine
  url: /calendar/
- title: Holon
  url: /holon/
- title: Wiki
  url: http://hasi.it/wiki
- title: Kontakt
  url: /contact/
- title: Unterstützen
  url: /support/

navigation_bottom:
- title: Archiv
  url: /blog/
- title: Vereinssatzung
  url: /site/satzung/
- title: Meta
  url: /meta/
- title: Impressum
  url: /site/notice/
