source: ./_source
destination: ./_site

name: HaSi e.V.
description: Dein Hackspace in Siegen
url: http://www.jekyll.hasi.it/
license: CC BY-NC-SA 3.0

excerpt_separator: "<!-- break -->"

podcast:
  description: bar
  subtitle: foo
  author: HaSi e.V.
  mail: podcast@hasi.it
  keywords: [octopod, podcast, magic] 
  itunes_categories: [Technology]

markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: table

assets:
  sources:
  - _assets/stylesheets
  - _assets/webfonts
  - _assets/images
  cachebust: none

info:
  name: Hasi e.v.
  mail: kontakt@hasi.it
  street: Effertsufer 104
  country: 57076 Siegen (NRW)

safe: false

navigation:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Vorträge
  url: /talks/
- title: Termine
  url: /calendar/
- title: Ideenalbum
  url: http://h42i.tumblr.com/
- title: Wiki
  url: http://hasi.it/wiki/Hauptseite

navigation_bottom:
- title: Impressum
  url: /site/notice/
- title: Vereinssatzung
  url: /site/satzung/
- title: Meta
  url: /meta/
