source: ./_source
destination: ./_site

name: HaSi e.V.
description: Dein Hackspace in Siegen
url: http://www.hasi.it

excerpt_separator: "<!-- break -->"

markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: table

assets:
  sources:
  - _assets/stylesheets
  - _assets/webfonts
  - _assets/images
  cachebust: none

info:
  name: Leon Rische
  mail: hello@l3kn.de
  street: Voßhölzchen 8 
  country: 57489 Drolshagen (NRW)

safe: false

navigation:
- title: Home
  url: /index.html
- title: Blog
  url: /blog/
- title: Vorträge
  url: /talks/
- title: Wiki
  url: http://hasi.it/wiki/Hauptseite
